#pragma once

#define IDA_SWITCH_EXPAND_AND_FORWARD(IN_RECEIVER, ...) \
  IN_RECEIVER(__VA_ARGS__)

#define IDA_SWITCH_PREPEND_STRINGIZER(IN_TOKEN) \
  #IN_TOKEN

#define IDA_SWITCH_STRINGIZE_A(IN_TOKEN) \
  IDA_SWITCH_EXPAND_AND_FORWARD(IDA_SWITCH_PREPEND_STRINGIZER, IN_TOKEN)

#define IDA_SWITCH_PREPEND_WIDE(IN_TOKEN) \
  L ## IN_TOKEN

#define IDA_SWITCH_STRINGIZE_W(IN_TOKEN) \
  IDA_SWITCH_EXPAND_AND_FORWARD(IDA_SWITCH_PREPEND_WIDE, IDA_SWITCH_STRINGIZE_A(IN_TOKEN))
